"""Transparency labels — the reader-facing text shown on the platform.

Maps an attribution verdict + confidence score to one of three plain-language
label variants (see planning.md §3 and the README). The label text changes with
the confidence score, so a 0.51 result and a 0.95 result read very differently.

The AI variant deliberately carries the most hedging and an explicit appeal
invitation — the false-positive asymmetry: wrongly accusing a human is the costly
error, so that verdict works hardest to be fair and offers recourse.
"""

from config import ATTR_AI, ATTR_HUMAN


def label_for(attribution: str, confidence: float) -> str:
    """Return the transparency-label text for a verdict + confidence.

    `confidence` is in [0,1] and is rendered as a whole percentage. Any
    unrecognized attribution falls through to the "uncertain" variant (fail safe).
    """
    conf_pct = round(confidence * 100)

    if attribution == ATTR_AI:
        return (
            f"🤖 Likely AI-generated. Multiple independent signals suggest this text was "
            f"probably produced by an AI system (our certainty: {conf_pct}%). Automated "
            f"detection is not perfect and can misclassify original human writing. If you "
            f"wrote this yourself, you can appeal this result and a person will review it."
        )

    if attribution == ATTR_HUMAN:
        return (
            f"✍️ Likely written by a human. Our analysis found the writing patterns and "
            f"style consistent with human authorship (our certainty: {conf_pct}%). This is "
            f"an automated assessment, not a guarantee. If you believe it's wrong, you can "
            f"appeal."
        )

    # uncertain (and the fail-safe default for any unrecognized verdict)
    return (
        f"❓ Attribution uncertain. Our signals disagree or aren't strong enough to reliably "
        f"determine whether this text was written by a human or generated by AI (our "
        f"certainty: {conf_pct}%). We are not making a determination — please treat this as "
        f"inconclusive rather than as evidence either way."
    )
