"""Signal 1 — LLM-as-judge (semantic), via Groq.

Asks the model whether a piece of text reads as human-written or AI-generated
and returns a single AI-likelihood in [0, 1] plus a one-line reason. This is the
*semantic* signal (see planning.md §1). It is deliberately conservative: any
failure to call or parse the model returns a neutral 0.5 (fail closed), so a
transient error can never nudge a submission toward an AI accusation.
"""

import re

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL, LLM_FAILSAFE_SCORE

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a forensic text-attribution analyst. Your only job is to judge "
    "whether a passage of text was written by a human or generated by an AI "
    "language model. Base your judgment on style, phrasing, coherence, voice, "
    "and idiosyncrasy — human writing tends to be varied, uneven, and "
    "idiosyncratic, while AI writing tends to be smooth, generic, and evenly "
    "balanced. You are not perfect and should express genuine uncertainty when "
    "the text is ambiguous.\n\n"
    "Respond in EXACTLY this format and nothing else:\n"
    "AI_LIKELIHOOD: <an integer from 0 to 100, where 0 = certainly human and "
    "100 = certainly AI>\n"
    "REASON: <one sentence explaining your judgment>"
)


def _parse(raw: str) -> dict:
    """Extract llm_score in [0,1] and a reason from the model's raw text.

    Fails closed to LLM_FAILSAFE_SCORE if the likelihood can't be found.
    """
    likelihood_match = re.search(r"AI_LIKELIHOOD:\s*(\d{1,3})", raw, re.IGNORECASE)
    reason_match = re.search(r"REASON:\s*(.+)", raw, re.IGNORECASE | re.DOTALL)

    if not likelihood_match:
        return {
            "llm_score": LLM_FAILSAFE_SCORE,
            "reason": "Could not parse model output; defaulted to neutral.",
            "raw": raw,
        }

    likelihood = int(likelihood_match.group(1))
    likelihood = max(0, min(100, likelihood))  # clamp to 0–100
    reason = reason_match.group(1).strip() if reason_match else "(no reason given)"

    return {
        "llm_score": round(likelihood / 100, 4),
        "reason": reason,
        "raw": raw,
    }


def classify_llm(text: str) -> dict:
    """Classify `text` with the LLM signal.

    Returns:
        {
          "llm_score": float in [0,1]   # probability the text is AI-generated
          "reason":    str              # one-line explanation
          "raw":       str              # the model's raw response (for auditing)
        }
    """
    try:
        completion = _client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,  # keep the judge as stable as possible
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = completion.choices[0].message.content or ""
        return _parse(raw)
    except Exception as exc:  # network error, auth, rate limit, etc. -> fail closed
        return {
            "llm_score": LLM_FAILSAFE_SCORE,
            "reason": f"LLM call failed ({type(exc).__name__}); defaulted to neutral.",
            "raw": "",
        }
